[project]
name = "homelab-ansible"
version = "0.1.0"
description = "Homelab Ansible Playbooks"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ansible>=13.2.0",
    "ansible-lint>=25.12.2",
]
